// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: api/devops/v1/devops.proto

package devopsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EnrollmentService_Enroll_FullMethodName = "/devops.v1.EnrollmentService/Enroll"
	EnrollmentService_Renew_FullMethodName  = "/devops.v1.EnrollmentService/Renew"
)

// EnrollmentServiceClient is the client API for EnrollmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Compatibility: never reuse field numbers or enum values; reserve removed
// fields; add messages or repeated/map fields freely, and mark new proto3 scalar
// fields optional when wire presence matters. Incompatible behavior requires devops.v2.
type EnrollmentServiceClient interface {
	Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
	Renew(ctx context.Context, in *RenewRequest, opts ...grpc.CallOption) (*RenewResponse, error)
}

type enrollmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEnrollmentServiceClient(cc grpc.ClientConnInterface) EnrollmentServiceClient {
	return &enrollmentServiceClient{cc}
}

func (c *enrollmentServiceClient) Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollResponse)
	err := c.cc.Invoke(ctx, EnrollmentService_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrollmentServiceClient) Renew(ctx context.Context, in *RenewRequest, opts ...grpc.CallOption) (*RenewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewResponse)
	err := c.cc.Invoke(ctx, EnrollmentService_Renew_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnrollmentServiceServer is the server API for EnrollmentService service.
// All implementations must embed UnimplementedEnrollmentServiceServer
// for forward compatibility.
//
// Compatibility: never reuse field numbers or enum values; reserve removed
// fields; add messages or repeated/map fields freely, and mark new proto3 scalar
// fields optional when wire presence matters. Incompatible behavior requires devops.v2.
type EnrollmentServiceServer interface {
	Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error)
	Renew(context.Context, *RenewRequest) (*RenewResponse, error)
	mustEmbedUnimplementedEnrollmentServiceServer()
}

// UnimplementedEnrollmentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnrollmentServiceServer struct{}

func (UnimplementedEnrollmentServiceServer) Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedEnrollmentServiceServer) Renew(context.Context, *RenewRequest) (*RenewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Renew not implemented")
}
func (UnimplementedEnrollmentServiceServer) mustEmbedUnimplementedEnrollmentServiceServer() {}
func (UnimplementedEnrollmentServiceServer) testEmbeddedByValue()                           {}

// UnsafeEnrollmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnrollmentServiceServer will
// result in compilation errors.
type UnsafeEnrollmentServiceServer interface {
	mustEmbedUnimplementedEnrollmentServiceServer()
}

func RegisterEnrollmentServiceServer(s grpc.ServiceRegistrar, srv EnrollmentServiceServer) {
	// If the following call panics, it indicates UnimplementedEnrollmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EnrollmentService_ServiceDesc, srv)
}

func _EnrollmentService_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrollmentServiceServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrollmentService_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrollmentServiceServer).Enroll(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnrollmentService_Renew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrollmentServiceServer).Renew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrollmentService_Renew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrollmentServiceServer).Renew(ctx, req.(*RenewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EnrollmentService_ServiceDesc is the grpc.ServiceDesc for EnrollmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnrollmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "devops.v1.EnrollmentService",
	HandlerType: (*EnrollmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enroll",
			Handler:    _EnrollmentService_Enroll_Handler,
		},
		{
			MethodName: "Renew",
			Handler:    _EnrollmentService_Renew_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/devops/v1/devops.proto",
}

const (
	AgentService_Connect_FullMethodName    = "/devops.v1.AgentService/Connect"
	AgentService_OpenTunnel_FullMethodName = "/devops.v1.AgentService/OpenTunnel"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ValidatorMessage], error)
	OpenTunnel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TunnelFrame, TunnelFrame], error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ValidatorMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, ValidatorMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ConnectClient = grpc.BidiStreamingClient[AgentMessage, ValidatorMessage]

func (c *agentServiceClient) OpenTunnel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TunnelFrame, TunnelFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[1], AgentService_OpenTunnel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TunnelFrame, TunnelFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_OpenTunnelClient = grpc.BidiStreamingClient[TunnelFrame, TunnelFrame]

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
type AgentServiceServer interface {
	Connect(grpc.BidiStreamingServer[AgentMessage, ValidatorMessage]) error
	OpenTunnel(grpc.BidiStreamingServer[TunnelFrame, TunnelFrame]) error
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Connect(grpc.BidiStreamingServer[AgentMessage, ValidatorMessage]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAgentServiceServer) OpenTunnel(grpc.BidiStreamingServer[TunnelFrame, TunnelFrame]) error {
	return status.Error(codes.Unimplemented, "method OpenTunnel not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).Connect(&grpc.GenericServerStream[AgentMessage, ValidatorMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ConnectServer = grpc.BidiStreamingServer[AgentMessage, ValidatorMessage]

func _AgentService_OpenTunnel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).OpenTunnel(&grpc.GenericServerStream[TunnelFrame, TunnelFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_OpenTunnelServer = grpc.BidiStreamingServer[TunnelFrame, TunnelFrame]

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "devops.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AgentService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "OpenTunnel",
			Handler:       _AgentService_OpenTunnel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/devops/v1/devops.proto",
}

const (
	AuthService_Login_FullMethodName                  = "/devops.v1.AuthService/Login"
	AuthService_RedeemClientInvitation_FullMethodName = "/devops.v1.AuthService/RedeemClientInvitation"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	RedeemClientInvitation(ctx context.Context, in *RedeemClientInvitationRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, AuthService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RedeemClientInvitation(ctx context.Context, in *RedeemClientInvitationRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, AuthService_RedeemClientInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
type AuthServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	RedeemClientInvitation(context.Context, *RedeemClientInvitationRequest) (*LoginResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthServiceServer) RedeemClientInvitation(context.Context, *RedeemClientInvitationRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RedeemClientInvitation not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RedeemClientInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedeemClientInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RedeemClientInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RedeemClientInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RedeemClientInvitation(ctx, req.(*RedeemClientInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "devops.v1.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
		{
			MethodName: "RedeemClientInvitation",
			Handler:    _AuthService_RedeemClientInvitation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/devops/v1/devops.proto",
}

const (
	FleetService_ListAgents_FullMethodName             = "/devops.v1.FleetService/ListAgents"
	FleetService_GetAgent_FullMethodName               = "/devops.v1.FleetService/GetAgent"
	FleetService_GetMetrics_FullMethodName             = "/devops.v1.FleetService/GetMetrics"
	FleetService_ListProcesses_FullMethodName          = "/devops.v1.FleetService/ListProcesses"
	FleetService_ListServices_FullMethodName           = "/devops.v1.FleetService/ListServices"
	FleetService_GetService_FullMethodName             = "/devops.v1.FleetService/GetService"
	FleetService_StartService_FullMethodName           = "/devops.v1.FleetService/StartService"
	FleetService_StopService_FullMethodName            = "/devops.v1.FleetService/StopService"
	FleetService_RestartService_FullMethodName         = "/devops.v1.FleetService/RestartService"
	FleetService_ReadLogs_FullMethodName               = "/devops.v1.FleetService/ReadLogs"
	FleetService_PreviewCleanup_FullMethodName         = "/devops.v1.FleetService/PreviewCleanup"
	FleetService_RunCleanup_FullMethodName             = "/devops.v1.FleetService/RunCleanup"
	FleetService_Reboot_FullMethodName                 = "/devops.v1.FleetService/Reboot"
	FleetService_Exec_FullMethodName                   = "/devops.v1.FleetService/Exec"
	FleetService_CancelJob_FullMethodName              = "/devops.v1.FleetService/CancelJob"
	FleetService_StreamJobOutput_FullMethodName        = "/devops.v1.FleetService/StreamJobOutput"
	FleetService_PrepareSsh_FullMethodName             = "/devops.v1.FleetService/PrepareSsh"
	FleetService_GetSshSession_FullMethodName          = "/devops.v1.FleetService/GetSshSession"
	FleetService_CloseSsh_FullMethodName               = "/devops.v1.FleetService/CloseSsh"
	FleetService_BridgeSsh_FullMethodName              = "/devops.v1.FleetService/BridgeSsh"
	FleetService_ListAudit_FullMethodName              = "/devops.v1.FleetService/ListAudit"
	FleetService_CreateEnrollmentToken_FullMethodName  = "/devops.v1.FleetService/CreateEnrollmentToken"
	FleetService_ListEnrollmentTokens_FullMethodName   = "/devops.v1.FleetService/ListEnrollmentTokens"
	FleetService_RevokeEnrollmentToken_FullMethodName  = "/devops.v1.FleetService/RevokeEnrollmentToken"
	FleetService_RevokeAgent_FullMethodName            = "/devops.v1.FleetService/RevokeAgent"
	FleetService_CreateUser_FullMethodName             = "/devops.v1.FleetService/CreateUser"
	FleetService_ListUsers_FullMethodName              = "/devops.v1.FleetService/ListUsers"
	FleetService_SetUserRole_FullMethodName            = "/devops.v1.FleetService/SetUserRole"
	FleetService_CreateClientInvitation_FullMethodName = "/devops.v1.FleetService/CreateClientInvitation"
	FleetService_ListClientInvitations_FullMethodName  = "/devops.v1.FleetService/ListClientInvitations"
	FleetService_RevokeClientInvitation_FullMethodName = "/devops.v1.FleetService/RevokeClientInvitation"
	FleetService_AddSshKey_FullMethodName              = "/devops.v1.FleetService/AddSshKey"
	FleetService_ListSshKeys_FullMethodName            = "/devops.v1.FleetService/ListSshKeys"
	FleetService_DeleteSshKey_FullMethodName           = "/devops.v1.FleetService/DeleteSshKey"
)

// FleetServiceClient is the client API for FleetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FleetServiceClient interface {
	ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error)
	GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*Agent, error)
	GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error)
	ListProcesses(ctx context.Context, in *ProcessListJobRequest, opts ...grpc.CallOption) (*Job, error)
	ListServices(ctx context.Context, in *ServiceListJobRequest, opts ...grpc.CallOption) (*Job, error)
	GetService(ctx context.Context, in *ServiceJobRequest, opts ...grpc.CallOption) (*Job, error)
	StartService(ctx context.Context, in *ServiceJobRequest, opts ...grpc.CallOption) (*Job, error)
	StopService(ctx context.Context, in *ServiceJobRequest, opts ...grpc.CallOption) (*Job, error)
	RestartService(ctx context.Context, in *ServiceJobRequest, opts ...grpc.CallOption) (*Job, error)
	ReadLogs(ctx context.Context, in *JournalJobRequest, opts ...grpc.CallOption) (*Job, error)
	PreviewCleanup(ctx context.Context, in *CleanupPreviewJobRequest, opts ...grpc.CallOption) (*Job, error)
	RunCleanup(ctx context.Context, in *CleanupRunJobRequest, opts ...grpc.CallOption) (*Job, error)
	Reboot(ctx context.Context, in *RebootJobRequest, opts ...grpc.CallOption) (*Job, error)
	Exec(ctx context.Context, in *ExecJobRequest, opts ...grpc.CallOption) (*Job, error)
	CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*Job, error)
	StreamJobOutput(ctx context.Context, in *StreamJobOutputRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OutputChunk], error)
	PrepareSsh(ctx context.Context, in *PrepareSshRequest, opts ...grpc.CallOption) (*SshSession, error)
	GetSshSession(ctx context.Context, in *GetSshSessionRequest, opts ...grpc.CallOption) (*SshSession, error)
	CloseSsh(ctx context.Context, in *CloseSshRequest, opts ...grpc.CallOption) (*SshSession, error)
	BridgeSsh(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TunnelFrame, TunnelFrame], error)
	ListAudit(ctx context.Context, in *ListAuditRequest, opts ...grpc.CallOption) (*ListAuditResponse, error)
	CreateEnrollmentToken(ctx context.Context, in *CreateEnrollmentTokenRequest, opts ...grpc.CallOption) (*EnrollmentToken, error)
	ListEnrollmentTokens(ctx context.Context, in *ListEnrollmentTokensRequest, opts ...grpc.CallOption) (*ListEnrollmentTokensResponse, error)
	RevokeEnrollmentToken(ctx context.Context, in *RevokeEnrollmentTokenRequest, opts ...grpc.CallOption) (*EnrollmentToken, error)
	RevokeAgent(ctx context.Context, in *RevokeAgentRequest, opts ...grpc.CallOption) (*Agent, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	SetUserRole(ctx context.Context, in *SetUserRoleRequest, opts ...grpc.CallOption) (*User, error)
	CreateClientInvitation(ctx context.Context, in *CreateClientInvitationRequest, opts ...grpc.CallOption) (*ClientInvitation, error)
	ListClientInvitations(ctx context.Context, in *ListClientInvitationsRequest, opts ...grpc.CallOption) (*ListClientInvitationsResponse, error)
	RevokeClientInvitation(ctx context.Context, in *RevokeClientInvitationRequest, opts ...grpc.CallOption) (*ClientInvitation, error)
	AddSshKey(ctx context.Context, in *AddSshKeyRequest, opts ...grpc.CallOption) (*SshKey, error)
	ListSshKeys(ctx context.Context, in *ListSshKeysRequest, opts ...grpc.CallOption) (*ListSshKeysResponse, error)
	DeleteSshKey(ctx context.Context, in *DeleteSshKeyRequest, opts ...grpc.CallOption) (*DeleteSshKeyResponse, error)
}

type fleetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFleetServiceClient(cc grpc.ClientConnInterface) FleetServiceClient {
	return &fleetServiceClient{cc}
}

func (c *fleetServiceClient) ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentsResponse)
	err := c.cc.Invoke(ctx, FleetService_ListAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*Agent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Agent)
	err := c.cc.Invoke(ctx, FleetService_GetAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetricsResponse)
	err := c.cc.Invoke(ctx, FleetService_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) ListProcesses(ctx context.Context, in *ProcessListJobRequest, opts ...grpc.CallOption) (*Job, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Job)
	err := c.cc.Invoke(ctx, FleetService_ListProcesses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) ListServices(ctx context.Context, in *ServiceListJobRequest, opts ...grpc.CallOption) (*Job, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Job)
	err := c.cc.Invoke(ctx, FleetService_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) GetService(ctx context.Context, in *ServiceJobRequest, opts ...grpc.CallOption) (*Job, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Job)
	err := c.cc.Invoke(ctx, FleetService_GetService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) StartService(ctx context.Context, in *ServiceJobRequest, opts ...grpc.CallOption) (*Job, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Job)
	err := c.cc.Invoke(ctx, FleetService_StartService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) StopService(ctx context.Context, in *ServiceJobRequest, opts ...grpc.CallOption) (*Job, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Job)
	err := c.cc.Invoke(ctx, FleetService_StopService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) RestartService(ctx context.Context, in *ServiceJobRequest, opts ...grpc.CallOption) (*Job, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Job)
	err := c.cc.Invoke(ctx, FleetService_RestartService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) ReadLogs(ctx context.Context, in *JournalJobRequest, opts ...grpc.CallOption) (*Job, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Job)
	err := c.cc.Invoke(ctx, FleetService_ReadLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) PreviewCleanup(ctx context.Context, in *CleanupPreviewJobRequest, opts ...grpc.CallOption) (*Job, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Job)
	err := c.cc.Invoke(ctx, FleetService_PreviewCleanup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) RunCleanup(ctx context.Context, in *CleanupRunJobRequest, opts ...grpc.CallOption) (*Job, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Job)
	err := c.cc.Invoke(ctx, FleetService_RunCleanup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) Reboot(ctx context.Context, in *RebootJobRequest, opts ...grpc.CallOption) (*Job, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Job)
	err := c.cc.Invoke(ctx, FleetService_Reboot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) Exec(ctx context.Context, in *ExecJobRequest, opts ...grpc.CallOption) (*Job, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Job)
	err := c.cc.Invoke(ctx, FleetService_Exec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*Job, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Job)
	err := c.cc.Invoke(ctx, FleetService_CancelJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) StreamJobOutput(ctx context.Context, in *StreamJobOutputRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OutputChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FleetService_ServiceDesc.Streams[0], FleetService_StreamJobOutput_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamJobOutputRequest, OutputChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetService_StreamJobOutputClient = grpc.ServerStreamingClient[OutputChunk]

func (c *fleetServiceClient) PrepareSsh(ctx context.Context, in *PrepareSshRequest, opts ...grpc.CallOption) (*SshSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SshSession)
	err := c.cc.Invoke(ctx, FleetService_PrepareSsh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) GetSshSession(ctx context.Context, in *GetSshSessionRequest, opts ...grpc.CallOption) (*SshSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SshSession)
	err := c.cc.Invoke(ctx, FleetService_GetSshSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) CloseSsh(ctx context.Context, in *CloseSshRequest, opts ...grpc.CallOption) (*SshSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SshSession)
	err := c.cc.Invoke(ctx, FleetService_CloseSsh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) BridgeSsh(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TunnelFrame, TunnelFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FleetService_ServiceDesc.Streams[1], FleetService_BridgeSsh_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TunnelFrame, TunnelFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetService_BridgeSshClient = grpc.BidiStreamingClient[TunnelFrame, TunnelFrame]

func (c *fleetServiceClient) ListAudit(ctx context.Context, in *ListAuditRequest, opts ...grpc.CallOption) (*ListAuditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAuditResponse)
	err := c.cc.Invoke(ctx, FleetService_ListAudit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) CreateEnrollmentToken(ctx context.Context, in *CreateEnrollmentTokenRequest, opts ...grpc.CallOption) (*EnrollmentToken, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollmentToken)
	err := c.cc.Invoke(ctx, FleetService_CreateEnrollmentToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) ListEnrollmentTokens(ctx context.Context, in *ListEnrollmentTokensRequest, opts ...grpc.CallOption) (*ListEnrollmentTokensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEnrollmentTokensResponse)
	err := c.cc.Invoke(ctx, FleetService_ListEnrollmentTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) RevokeEnrollmentToken(ctx context.Context, in *RevokeEnrollmentTokenRequest, opts ...grpc.CallOption) (*EnrollmentToken, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollmentToken)
	err := c.cc.Invoke(ctx, FleetService_RevokeEnrollmentToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) RevokeAgent(ctx context.Context, in *RevokeAgentRequest, opts ...grpc.CallOption) (*Agent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Agent)
	err := c.cc.Invoke(ctx, FleetService_RevokeAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, FleetService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, FleetService_ListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) SetUserRole(ctx context.Context, in *SetUserRoleRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, FleetService_SetUserRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) CreateClientInvitation(ctx context.Context, in *CreateClientInvitationRequest, opts ...grpc.CallOption) (*ClientInvitation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientInvitation)
	err := c.cc.Invoke(ctx, FleetService_CreateClientInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) ListClientInvitations(ctx context.Context, in *ListClientInvitationsRequest, opts ...grpc.CallOption) (*ListClientInvitationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListClientInvitationsResponse)
	err := c.cc.Invoke(ctx, FleetService_ListClientInvitations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) RevokeClientInvitation(ctx context.Context, in *RevokeClientInvitationRequest, opts ...grpc.CallOption) (*ClientInvitation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientInvitation)
	err := c.cc.Invoke(ctx, FleetService_RevokeClientInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) AddSshKey(ctx context.Context, in *AddSshKeyRequest, opts ...grpc.CallOption) (*SshKey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SshKey)
	err := c.cc.Invoke(ctx, FleetService_AddSshKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) ListSshKeys(ctx context.Context, in *ListSshKeysRequest, opts ...grpc.CallOption) (*ListSshKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSshKeysResponse)
	err := c.cc.Invoke(ctx, FleetService_ListSshKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) DeleteSshKey(ctx context.Context, in *DeleteSshKeyRequest, opts ...grpc.CallOption) (*DeleteSshKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSshKeyResponse)
	err := c.cc.Invoke(ctx, FleetService_DeleteSshKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FleetServiceServer is the server API for FleetService service.
// All implementations must embed UnimplementedFleetServiceServer
// for forward compatibility.
type FleetServiceServer interface {
	ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error)
	GetAgent(context.Context, *GetAgentRequest) (*Agent, error)
	GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error)
	ListProcesses(context.Context, *ProcessListJobRequest) (*Job, error)
	ListServices(context.Context, *ServiceListJobRequest) (*Job, error)
	GetService(context.Context, *ServiceJobRequest) (*Job, error)
	StartService(context.Context, *ServiceJobRequest) (*Job, error)
	StopService(context.Context, *ServiceJobRequest) (*Job, error)
	RestartService(context.Context, *ServiceJobRequest) (*Job, error)
	ReadLogs(context.Context, *JournalJobRequest) (*Job, error)
	PreviewCleanup(context.Context, *CleanupPreviewJobRequest) (*Job, error)
	RunCleanup(context.Context, *CleanupRunJobRequest) (*Job, error)
	Reboot(context.Context, *RebootJobRequest) (*Job, error)
	Exec(context.Context, *ExecJobRequest) (*Job, error)
	CancelJob(context.Context, *CancelJobRequest) (*Job, error)
	StreamJobOutput(*StreamJobOutputRequest, grpc.ServerStreamingServer[OutputChunk]) error
	PrepareSsh(context.Context, *PrepareSshRequest) (*SshSession, error)
	GetSshSession(context.Context, *GetSshSessionRequest) (*SshSession, error)
	CloseSsh(context.Context, *CloseSshRequest) (*SshSession, error)
	BridgeSsh(grpc.BidiStreamingServer[TunnelFrame, TunnelFrame]) error
	ListAudit(context.Context, *ListAuditRequest) (*ListAuditResponse, error)
	CreateEnrollmentToken(context.Context, *CreateEnrollmentTokenRequest) (*EnrollmentToken, error)
	ListEnrollmentTokens(context.Context, *ListEnrollmentTokensRequest) (*ListEnrollmentTokensResponse, error)
	RevokeEnrollmentToken(context.Context, *RevokeEnrollmentTokenRequest) (*EnrollmentToken, error)
	RevokeAgent(context.Context, *RevokeAgentRequest) (*Agent, error)
	CreateUser(context.Context, *CreateUserRequest) (*User, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	SetUserRole(context.Context, *SetUserRoleRequest) (*User, error)
	CreateClientInvitation(context.Context, *CreateClientInvitationRequest) (*ClientInvitation, error)
	ListClientInvitations(context.Context, *ListClientInvitationsRequest) (*ListClientInvitationsResponse, error)
	RevokeClientInvitation(context.Context, *RevokeClientInvitationRequest) (*ClientInvitation, error)
	AddSshKey(context.Context, *AddSshKeyRequest) (*SshKey, error)
	ListSshKeys(context.Context, *ListSshKeysRequest) (*ListSshKeysResponse, error)
	DeleteSshKey(context.Context, *DeleteSshKeyRequest) (*DeleteSshKeyResponse, error)
	mustEmbedUnimplementedFleetServiceServer()
}

// UnimplementedFleetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFleetServiceServer struct{}

func (UnimplementedFleetServiceServer) ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedFleetServiceServer) GetAgent(context.Context, *GetAgentRequest) (*Agent, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgent not implemented")
}
func (UnimplementedFleetServiceServer) GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedFleetServiceServer) ListProcesses(context.Context, *ProcessListJobRequest) (*Job, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProcesses not implemented")
}
func (UnimplementedFleetServiceServer) ListServices(context.Context, *ServiceListJobRequest) (*Job, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedFleetServiceServer) GetService(context.Context, *ServiceJobRequest) (*Job, error) {
	return nil, status.Error(codes.Unimplemented, "method GetService not implemented")
}
func (UnimplementedFleetServiceServer) StartService(context.Context, *ServiceJobRequest) (*Job, error) {
	return nil, status.Error(codes.Unimplemented, "method StartService not implemented")
}
func (UnimplementedFleetServiceServer) StopService(context.Context, *ServiceJobRequest) (*Job, error) {
	return nil, status.Error(codes.Unimplemented, "method StopService not implemented")
}
func (UnimplementedFleetServiceServer) RestartService(context.Context, *ServiceJobRequest) (*Job, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartService not implemented")
}
func (UnimplementedFleetServiceServer) ReadLogs(context.Context, *JournalJobRequest) (*Job, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadLogs not implemented")
}
func (UnimplementedFleetServiceServer) PreviewCleanup(context.Context, *CleanupPreviewJobRequest) (*Job, error) {
	return nil, status.Error(codes.Unimplemented, "method PreviewCleanup not implemented")
}
func (UnimplementedFleetServiceServer) RunCleanup(context.Context, *CleanupRunJobRequest) (*Job, error) {
	return nil, status.Error(codes.Unimplemented, "method RunCleanup not implemented")
}
func (UnimplementedFleetServiceServer) Reboot(context.Context, *RebootJobRequest) (*Job, error) {
	return nil, status.Error(codes.Unimplemented, "method Reboot not implemented")
}
func (UnimplementedFleetServiceServer) Exec(context.Context, *ExecJobRequest) (*Job, error) {
	return nil, status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedFleetServiceServer) CancelJob(context.Context, *CancelJobRequest) (*Job, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelJob not implemented")
}
func (UnimplementedFleetServiceServer) StreamJobOutput(*StreamJobOutputRequest, grpc.ServerStreamingServer[OutputChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamJobOutput not implemented")
}
func (UnimplementedFleetServiceServer) PrepareSsh(context.Context, *PrepareSshRequest) (*SshSession, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareSsh not implemented")
}
func (UnimplementedFleetServiceServer) GetSshSession(context.Context, *GetSshSessionRequest) (*SshSession, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSshSession not implemented")
}
func (UnimplementedFleetServiceServer) CloseSsh(context.Context, *CloseSshRequest) (*SshSession, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseSsh not implemented")
}
func (UnimplementedFleetServiceServer) BridgeSsh(grpc.BidiStreamingServer[TunnelFrame, TunnelFrame]) error {
	return status.Error(codes.Unimplemented, "method BridgeSsh not implemented")
}
func (UnimplementedFleetServiceServer) ListAudit(context.Context, *ListAuditRequest) (*ListAuditResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAudit not implemented")
}
func (UnimplementedFleetServiceServer) CreateEnrollmentToken(context.Context, *CreateEnrollmentTokenRequest) (*EnrollmentToken, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEnrollmentToken not implemented")
}
func (UnimplementedFleetServiceServer) ListEnrollmentTokens(context.Context, *ListEnrollmentTokensRequest) (*ListEnrollmentTokensResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEnrollmentTokens not implemented")
}
func (UnimplementedFleetServiceServer) RevokeEnrollmentToken(context.Context, *RevokeEnrollmentTokenRequest) (*EnrollmentToken, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeEnrollmentToken not implemented")
}
func (UnimplementedFleetServiceServer) RevokeAgent(context.Context, *RevokeAgentRequest) (*Agent, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeAgent not implemented")
}
func (UnimplementedFleetServiceServer) CreateUser(context.Context, *CreateUserRequest) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedFleetServiceServer) ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedFleetServiceServer) SetUserRole(context.Context, *SetUserRoleRequest) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method SetUserRole not implemented")
}
func (UnimplementedFleetServiceServer) CreateClientInvitation(context.Context, *CreateClientInvitationRequest) (*ClientInvitation, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateClientInvitation not implemented")
}
func (UnimplementedFleetServiceServer) ListClientInvitations(context.Context, *ListClientInvitationsRequest) (*ListClientInvitationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListClientInvitations not implemented")
}
func (UnimplementedFleetServiceServer) RevokeClientInvitation(context.Context, *RevokeClientInvitationRequest) (*ClientInvitation, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeClientInvitation not implemented")
}
func (UnimplementedFleetServiceServer) AddSshKey(context.Context, *AddSshKeyRequest) (*SshKey, error) {
	return nil, status.Error(codes.Unimplemented, "method AddSshKey not implemented")
}
func (UnimplementedFleetServiceServer) ListSshKeys(context.Context, *ListSshKeysRequest) (*ListSshKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSshKeys not implemented")
}
func (UnimplementedFleetServiceServer) DeleteSshKey(context.Context, *DeleteSshKeyRequest) (*DeleteSshKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSshKey not implemented")
}
func (UnimplementedFleetServiceServer) mustEmbedUnimplementedFleetServiceServer() {}
func (UnimplementedFleetServiceServer) testEmbeddedByValue()                      {}

// UnsafeFleetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FleetServiceServer will
// result in compilation errors.
type UnsafeFleetServiceServer interface {
	mustEmbedUnimplementedFleetServiceServer()
}

func RegisterFleetServiceServer(s grpc.ServiceRegistrar, srv FleetServiceServer) {
	// If the following call panics, it indicates UnimplementedFleetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FleetService_ServiceDesc, srv)
}

func _FleetService_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ListAgents(ctx, req.(*ListAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_GetAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).GetAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_GetAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).GetAgent(ctx, req.(*GetAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).GetMetrics(ctx, req.(*GetMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_ListProcesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessListJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ListProcesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ListProcesses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ListProcesses(ctx, req.(*ProcessListJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceListJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ListServices(ctx, req.(*ServiceListJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_GetService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).GetService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_GetService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).GetService(ctx, req.(*ServiceJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_StartService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).StartService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_StartService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).StartService(ctx, req.(*ServiceJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_StopService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).StopService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_StopService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).StopService(ctx, req.(*ServiceJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_RestartService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).RestartService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_RestartService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).RestartService(ctx, req.(*ServiceJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_ReadLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JournalJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ReadLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ReadLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ReadLogs(ctx, req.(*JournalJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_PreviewCleanup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanupPreviewJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).PreviewCleanup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_PreviewCleanup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).PreviewCleanup(ctx, req.(*CleanupPreviewJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_RunCleanup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanupRunJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).RunCleanup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_RunCleanup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).RunCleanup(ctx, req.(*CleanupRunJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_Reboot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebootJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).Reboot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_Reboot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).Reboot(ctx, req.(*RebootJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_Exec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).Exec(ctx, req.(*ExecJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_CancelJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).CancelJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_CancelJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).CancelJob(ctx, req.(*CancelJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_StreamJobOutput_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamJobOutputRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FleetServiceServer).StreamJobOutput(m, &grpc.GenericServerStream[StreamJobOutputRequest, OutputChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetService_StreamJobOutputServer = grpc.ServerStreamingServer[OutputChunk]

func _FleetService_PrepareSsh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareSshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).PrepareSsh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_PrepareSsh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).PrepareSsh(ctx, req.(*PrepareSshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_GetSshSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSshSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).GetSshSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_GetSshSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).GetSshSession(ctx, req.(*GetSshSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_CloseSsh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseSshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).CloseSsh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_CloseSsh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).CloseSsh(ctx, req.(*CloseSshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_BridgeSsh_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FleetServiceServer).BridgeSsh(&grpc.GenericServerStream[TunnelFrame, TunnelFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetService_BridgeSshServer = grpc.BidiStreamingServer[TunnelFrame, TunnelFrame]

func _FleetService_ListAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ListAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ListAudit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ListAudit(ctx, req.(*ListAuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_CreateEnrollmentToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEnrollmentTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).CreateEnrollmentToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_CreateEnrollmentToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).CreateEnrollmentToken(ctx, req.(*CreateEnrollmentTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_ListEnrollmentTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEnrollmentTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ListEnrollmentTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ListEnrollmentTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ListEnrollmentTokens(ctx, req.(*ListEnrollmentTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_RevokeEnrollmentToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeEnrollmentTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).RevokeEnrollmentToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_RevokeEnrollmentToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).RevokeEnrollmentToken(ctx, req.(*RevokeEnrollmentTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_RevokeAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).RevokeAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_RevokeAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).RevokeAgent(ctx, req.(*RevokeAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_SetUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).SetUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_SetUserRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).SetUserRole(ctx, req.(*SetUserRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_CreateClientInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClientInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).CreateClientInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_CreateClientInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).CreateClientInvitation(ctx, req.(*CreateClientInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_ListClientInvitations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClientInvitationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ListClientInvitations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ListClientInvitations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ListClientInvitations(ctx, req.(*ListClientInvitationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_RevokeClientInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeClientInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).RevokeClientInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_RevokeClientInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).RevokeClientInvitation(ctx, req.(*RevokeClientInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_AddSshKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSshKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).AddSshKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_AddSshKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).AddSshKey(ctx, req.(*AddSshKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_ListSshKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSshKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ListSshKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ListSshKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ListSshKeys(ctx, req.(*ListSshKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_DeleteSshKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSshKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).DeleteSshKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_DeleteSshKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).DeleteSshKey(ctx, req.(*DeleteSshKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FleetService_ServiceDesc is the grpc.ServiceDesc for FleetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FleetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "devops.v1.FleetService",
	HandlerType: (*FleetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAgents",
			Handler:    _FleetService_ListAgents_Handler,
		},
		{
			MethodName: "GetAgent",
			Handler:    _FleetService_GetAgent_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _FleetService_GetMetrics_Handler,
		},
		{
			MethodName: "ListProcesses",
			Handler:    _FleetService_ListProcesses_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _FleetService_ListServices_Handler,
		},
		{
			MethodName: "GetService",
			Handler:    _FleetService_GetService_Handler,
		},
		{
			MethodName: "StartService",
			Handler:    _FleetService_StartService_Handler,
		},
		{
			MethodName: "StopService",
			Handler:    _FleetService_StopService_Handler,
		},
		{
			MethodName: "RestartService",
			Handler:    _FleetService_RestartService_Handler,
		},
		{
			MethodName: "ReadLogs",
			Handler:    _FleetService_ReadLogs_Handler,
		},
		{
			MethodName: "PreviewCleanup",
			Handler:    _FleetService_PreviewCleanup_Handler,
		},
		{
			MethodName: "RunCleanup",
			Handler:    _FleetService_RunCleanup_Handler,
		},
		{
			MethodName: "Reboot",
			Handler:    _FleetService_Reboot_Handler,
		},
		{
			MethodName: "Exec",
			Handler:    _FleetService_Exec_Handler,
		},
		{
			MethodName: "CancelJob",
			Handler:    _FleetService_CancelJob_Handler,
		},
		{
			MethodName: "PrepareSsh",
			Handler:    _FleetService_PrepareSsh_Handler,
		},
		{
			MethodName: "GetSshSession",
			Handler:    _FleetService_GetSshSession_Handler,
		},
		{
			MethodName: "CloseSsh",
			Handler:    _FleetService_CloseSsh_Handler,
		},
		{
			MethodName: "ListAudit",
			Handler:    _FleetService_ListAudit_Handler,
		},
		{
			MethodName: "CreateEnrollmentToken",
			Handler:    _FleetService_CreateEnrollmentToken_Handler,
		},
		{
			MethodName: "ListEnrollmentTokens",
			Handler:    _FleetService_ListEnrollmentTokens_Handler,
		},
		{
			MethodName: "RevokeEnrollmentToken",
			Handler:    _FleetService_RevokeEnrollmentToken_Handler,
		},
		{
			MethodName: "RevokeAgent",
			Handler:    _FleetService_RevokeAgent_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _FleetService_CreateUser_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _FleetService_ListUsers_Handler,
		},
		{
			MethodName: "SetUserRole",
			Handler:    _FleetService_SetUserRole_Handler,
		},
		{
			MethodName: "CreateClientInvitation",
			Handler:    _FleetService_CreateClientInvitation_Handler,
		},
		{
			MethodName: "ListClientInvitations",
			Handler:    _FleetService_ListClientInvitations_Handler,
		},
		{
			MethodName: "RevokeClientInvitation",
			Handler:    _FleetService_RevokeClientInvitation_Handler,
		},
		{
			MethodName: "AddSshKey",
			Handler:    _FleetService_AddSshKey_Handler,
		},
		{
			MethodName: "ListSshKeys",
			Handler:    _FleetService_ListSshKeys_Handler,
		},
		{
			MethodName: "DeleteSshKey",
			Handler:    _FleetService_DeleteSshKey_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamJobOutput",
			Handler:       _FleetService_StreamJobOutput_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BridgeSsh",
			Handler:       _FleetService_BridgeSsh_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/devops/v1/devops.proto",
}
